import re
from langdetect import detect


def is_english(text):
    if text is None:
        return 'undefined'
    try:
        lang = detect(text)
        return lang == 'en'
    except:
        return 'undefined'


def re_write_text(data):

    if (data == None):
        lists = ''
    else:
        lists = data

    lists = re.sub(r'\bOur\b', 'Their', lists)
    lists = re.sub(r'\bour\b', 'their', lists)
    lists = re.sub(r'\bWe are\b', 'They are', lists)
    lists = re.sub(r'\bWe\'re\b', 'They\'re', lists)
    lists = re.sub(r'\bwe\'re\b', 'they\'re', lists)
    lists = re.sub(r'\bwe are\b', 'they are', lists)
    lists = re.sub(r'\bI\b', 'He/She', lists)
    lists = re.sub(r'\bWe\b', 'They', lists)
    lists = re.sub(r'\bwe\b', 'they', lists)

    return lists


def custom_slugify(text, separator="-", filter_top="yes"):
    stop_words = [
        "a",
        "about",
        "above",
        "across",
        "after",
        "afterwards",
        "again",
        "against",
        "all",
        "almost",
        "alone",
        "along",
        "already",
        "also",
        "although",
        "always",
        "am",
        "among",
        "amongst",
        "amoungst",
        "amount",
        "an",
        "and",
        "another",
        "any",
        "anyhow",
        "anyone",
        "anything",
        "anyway",
        "anywhere",
        "are",
        "around",
        "as",
        "at",
        "back",
        "be",
        "became",
        "because",
        "become",
        "becomes",
        "becoming",
        "been",
        "before",
        "beforehand",
        "behind",
        "being",
        "below",
        "beside",
        "besides",
        "between",
        "beyond",
        "bill",
        "both",
        "bottom",
        "but",
        "by",
        "call",
        "can",
        "cannot",
        "cant",
        "co",
        "computer",
        "con",
        "could",
        "couldnt",
        "cry",
        "de",
        "describe",
        "detail",
        "did",
        "do",
        "done",
        "down",
        "due",
        "during",
        "each",
        "eg",
        "eight",
        "either",
        "eleven",
        "else",
        "elsewhere",
        "empty",
        "enough",
        "etc",
        "even",
        "ever",
        "every",
        "everyone",
        "everything",
        "everywhere",
        "except",
        "few",
        "fifteen",
        "fify",
        "fill",
        "find",
        "fire",
        "first",
        "five",
        "for",
        "former",
        "formerly",
        "forty",
        "found",
        "four",
        "from",
        "front",
        "full",
        "further",
        "get",
        "give",
        "go",
        "had",
        "has",
        "hasnt",
        "have",
        "he",
        "hence",
        "her",
        "here",
        "hereafter",
        "hereby",
        "herein",
        "hereupon",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "however",
        "hundred",
        "i",
        "ie",
        "if",
        "in",
        "inc",
        "indeed",
        "interest",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "keep",
        "last",
        "latter",
        "latterly",
        "least",
        "less",
        "ltd",
        "made",
        "many",
        "may",
        "me",
        "meanwhile",
        "might",
        "mill",
        "mine",
        "more",
        "moreover",
        "most",
        "mostly",
        "move",
        "much",
        "must",
        "my",
        "myself",
        "name",
        "namely",
        "neither",
        "never",
        "nevertheless",
        "next",
        "nine",
        "no",
        "nobody",
        "none",
        "noone",
        "nor",
        "not",
        "nothing",
        "now",
        "nowhere",
        "of",
        "off",
        "often",
        "on",
        "once",
        "one",
        "only",
        "onto",
        "or",
        "other",
        "others",
        "otherwise",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "list",
        "own",
        "part",
        "per",
        "perhaps",
        "please",
        "put",
        "rather",
        "re",
        "said",
        "same",
        "see",
        "seem",
        "seemed",
        "seeming",
        "seems",
        "serious",
        "several",
        "she",
        "should",
        "show",
        "side",
        "since",
        "sincere",
        "six",
        "sixty",
        "so",
        "some",
        "somehow",
        "someone",
        "something",
        "sometime",
        "sometimes",
        "somewhere",
        "still",
        "such",
        "system",
        "take",
        "ten",
        "than",
        "that",
        "the",
        "their",
        "them",
        "themselves",
        "then",
        "thence",
        "there",
        "thereafter",
        "thereby",
        "therefore",
        "therein",
        "thereupon",
        "these",
        "they",
        "thick",
        "thin",
        "third",
        "this",
        "those",
        "though",
        "three",
        "through",
        "throughout",
        "thru",
        "thus",
        "to",
        "want",
        "together",
        "too",
        "top",
        "toward",
        "towards",
        "twelve",
        "twenty",
        "two",
        "un",
        "under",
        "until",
        "up",
        "upon",
        "us",
        "very",
        "via",
        "was",
        "we",
        "well",
        "were",
        "what",
        "whatever",
        "when",
        "whence",
        "whenever",
        "where",
        "whereafter",
        "whereas",
        "whereby",
        "wherein",
        "whereupon",
        "wherever",
        "whether",
        "which",
        "while",
        "whither",
        "who",
        "whoever",
        "whole",
        "whom",
        "whose",
        "why",
        "will",
        "with",
        "within",
        "without",
        "would",
        "yet",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "2024",
        "good morning",
        "good evening",
        "good afternoon",
        "good night",
        "thank you",
        "thanks",
        "don't",
        "okay",
        "alright",
        "thank you",
        "can't",
        "hi",
        "hello",
        "hey",
        "please",
        "ma",
        "prof",
        "u",
        "sir",
        "ok",
        "does",
        "&",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "plz",
    ]

    # Split into words
    text = strip_html_tags(text)
    words = text.split(" ")

    # Filter stop words
    words = [word for word in words if word.lower() not in stop_words]

    # Join words back together
    if filter_top == "yes":
        slug = "-".join(words)
        # Remove "top any number" anywhere in the string
        slug = re.sub(r"top-\d+\s*", "", slug, flags=re.IGNORECASE)
    else:
        slug = "-".join(words)

    # Additional cleaning
    slug = re.sub(r"{[^}]*}", "", slug)
    slug = re.sub(r"[^\w-]+", "-", slug)
    slug = slug.strip("-").replace("-+", "-").lower().strip()
    return slug


def strip_html_tags(html):
    if not isinstance(html, str):
        print("Expected a string")

    return re.sub(r'<[^>]*>', '', html)
